export const SET_LOGGED = 'SET_LOGGED'
export const LOG_OUT = 'LOG_OUT'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_REVIEWS = 'GET_REVIEWS'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING'

export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART'
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART'
export const ADD_PRODUCT_TO_SAVED = 'ADD_PRODUCT_TO_SAVED'
export const SUBTRACT_QTY_FROM_CART = 'SUBTRACT_QTY_FROM_CART'
export const REMOVE_PRODUCT_FROM_SAVED = 'REMOVE_PRODUCT_FROM_SAVED'
export const CLEAN_GUEST_CART = 'CLEAN_GUEST_CART'

export const SUBTRACT_QTY_FROM_SAVED = 'SUBTRACT_QTY_FROM_SAVED'
export const QTY_CHOOSE_FROM_CART = 'QTY_CHOOSE_FROM_CART'

export const GET_FAVORITES = 'GET_FAVORITES'
export const GET_CART = 'GET_CART'
export const GET_SAVED = 'GET_SAVED'
